version: "3.7"

services:
    backend:
        build: .
        working_dir: /app
        volumes:
            - .:/app
        ports:
            - 8000:8000
        command: "uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
